services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: peanutbutter
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: on-failure

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@email.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_EMAIL:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lig/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: on-failure

  companyservice:
    container_name: company
    image: dimitarrradev/companyservice
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    networks:
      - postgres
    restart: on-failure

  jobservice:
    container_name: job
    image: dimitarrradev/jobservice
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - postgres

  reviewservice:
    container_name: reviews
    image: dimitarrradev/reviewservice
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:

