services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: peanutbutter
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: on-failure

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@email.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_EMAIL:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lig/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: on-failure

#  zipkin:
#    container_name: zipkin
#    image: dimitarrradev/zipkin
#    ports:
#      - "9411:9411"
#    networks:
#      - backend
#    restart: always

  companyservice:
    container_name: company
    image: dimitarrradev/companyservice
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - serviceregistry
    networks:
      - backend
    restart: on-failure

  jobservice:
    container_name: job
    image: dimitarrradev/jobservice
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - serviceregistry
    restart: on-failure
    networks:
      - backend

  reviewservice:
    container_name: reviews
    image: dimitarrradev/reviewservice
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - serviceregistry
    restart: on-failure
    networks:
      - backend

  serviceregistry:
    container_name: registry
    image: dimitarrradev/serviceregistry
    ports:
      - "8761:8761"
    restart: on-failure
    networks:
      - backend

  configserver:
    container_name: configserver
    image: dimitarrradev/configserver
    ports:
      - "8888:8888"
    restart: on-failure
    depends_on:
      - serviceregistry
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres:
  pgadmin:

