spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: company-service
              uri: lb://COMPANY-SERVICE
              predicates:
                - Path=/companies/**

            - id: job-service
              uri: lb://JOB-SERVICE
              predicates:
                - Path=/jobs/**

            - id: review-service
              uri: lb://REVIEW-SERVICE
              predicates:
                - Path=/reviews/**

            - id: eureka-server
              uri: http://serviceregistry:8761
              predicates:
                - Path=/eureka/main
              filter:
                - SetPath=/

            - id: eureka-server-static
              uri: http://serviceregistry:8761
              predicates:
                - Path=/eureka/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://serviceregistry:8761/eureka/

    register-with-eureka: true
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1

server:
  port: 8086
