spring.application.name=company-service

#DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/company_service_db
spring.datasource.username=root
spring.datasource.password=peanutbutter
spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop

#ACTUATOR
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.shutdown.enabled=true

management.info.env.enabled=true

info.app.name=JobApplication
info.app.description=Job app for microservices

server.port=8083