spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          defaultLabel: master
          uri: https://github:com/DimitarRadev88/job-app-properties-repo:#EUREKA

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8888