spring.application.name=config-server

#EUREKA
eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.config.server.git.defaultLabel=master
spring.cloud.config.server.git.uri=https://github.com/DimitarRadev88/job-app-properties-repo

server.port=8888